name: acceptance

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/snapshot.json'  # Trigger only when snapshot.json files are modified

  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:
    # Define input parameters for manual workflow dispatch
    inputs:
      snapshot-paths:
        description: 'Path to the snapshot.json file to run tests on'
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  determine_snapshots:
    runs-on: ubuntu-latest
    outputs:
      snapshots: ${{ steps.set-snapshots.outputs.snapshots }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine snapshot.json paths
        id: set-snapshots
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            SNAPSHOT_FILES="${{ github.event.inputs.snapshot-paths }}"
          else
            SNAPSHOT_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep 'snapshot.json')
          fi

          if [[ -z "$SNAPSHOT_FILES" ]]; then
            echo "No snapshot.json files found or provided."
            exit 1
          fi

          SNAPSHOT_ARRAY=()
          for file in $SNAPSHOT_FILES; do
            SNAPSHOT_ARRAY+=("\"$file\"")
          done

          echo "snapshots=[${SNAPSHOT_ARRAY[*]}]" >> $GITHUB_OUTPUT

  structural_tests:
    needs: determine_snapshots
    runs-on: ubuntu-latest
    strategy:
      matrix:
        snapshot: ${{ fromJson(needs.determine_snapshots.outputs.snapshots) }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: securesign/structural-tests
          path: structural-tests

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2

      # Run the tests with the modified snapshot.json file path as input
      - name: Run tests
        run: |
          echo "Running tests for ${{ matrix.snapshot }}"
          cd structural-tests
          SNAPSHOT="${{ matrix.snapshot }}" go test ./...
